services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 65535:65535
    networks:
      - careerspeak
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../voice:/voice:rw

networks:
  careerspeak:
    external: true
